[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
seed = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shared = { path = "../shared" }
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.5"
